### PR TITLE
Resolve ember-try scenario failures

### LINKED ISSUE #61: Failing test scenarios
3 of the ember-try scenarios are failing after #55 merge (looks like tests didn't run there). Opening an issue to track:

```
ember-default-with-jquery
embroider-safe
embroider-optimized
```

### ember-defeault-with-jquery

Seems to be failing with:

```
Setting the `jquery-integration` optional feature flag to `true` was deprecated in Ember 3.x and removed in Ember 4.0.0. You must add the `@ember/optional-features` addon and set this feature to `false`.

For more information, see the deprecation guide: https://deprecations.emberjs.com/v3.x/#toc_optional-feature-jquery-integration
```

I tried adding this dependency into the ember try scenario, but it didn't seem to work (package was installed, but same failure message). It might make most sense to just drop this scenario. 

### embroider scenarios

Not sure what to do about these!

### PR DESCRIPTION
**Pull request by jleja**
Closes #61.

## Changes proposed in this pull request
- Updates `ember-default-with-jquery` to use `feature:enable jquery-integrations` in the test command.
- Allows Embroider scenarios to fail.  Fixing scenarios might be able to be handled with #46.

### CODE REVIEW

File: config/ember-try.js [hunk 1]
```diff
@@ -56,6 +56,7 @@ module.exports = async function () {
         npm: {
           devDependencies: {
             '@ember/jquery': '^1.1.0',
+            'ember-source': '~3.28.0',
```
Comment (mehulkar) [inline config/ember-try.js:59]: I thiiiink basd on the error message you'll also need `'@ember/optional-features': '~2.0.0',` here

Comment (mehulkar) [reply config/ember-try.js:59]: but i guess the suite is passing so 🤷🏾

Comment (jleja) [reply config/ember-try.js:59]: Up until 4.x, you just get a warning, which is why we don't need it if we pin the dependency.  Once `ember-source` is 4.x, then we need to not only include it, but also do something with the configuration.

Although, I think I have an idea.....

**Comment by mehulkar** [comment]
nice. 🚢 ?
